### ISSUE TITLE
'Nifti1Image' object has no attribute '_dataobj' in topic classification

### ISSUE THREAD

**Issue by AlexHatoum** [adelavega/neurosynth-mfc#1]
Hi,

I am attempting to run your code for a topic search from nifti images (profiles.ipynb) as it is on the github before I apply it to my own data.

When I get to

clf = RegionalClassifier(dataset, 'cluster_labels_k3.nii.gz', GaussianNB())
clf.classify(scoring=roc_auc_score)

I get the error
'Nifti1Image' object has no attribute '_dataobj

Do you have an intuition of what is occurring?

**Comment by AlexHatoum** [comment]
Additionally, I have been looking at this issue for a little while now, and I can get the classification process to work with the database.txt and features.txt files in base neurosynth, the issue only exists when I use one of your .pkl files.

**Comment by enderwiggin205** [comment]
Hey Alex,

I was having the same problem and I figured out a workaround. 

I downgraded nibabel to version 1.3.0, and then in nibabel's volumeutils.py, line 471, I changed:
`mode='c'` to `mode='w'`

Hope this helps.

**Comment by adelavega** [comment]
Hey, sorry I just saw this.

Are you using `nibabel==1.3.0`?

That's probably the source of the problem.

**Comment by boredStats** [comment]
Yes, that was the problem. Switching back to 1.3.0 works.

**Comment by adelavega** [comment]
Great! It seems there are two issues here:

1) Complicated/fragile dependencies. The nibabel issue in particular has always been popping up, and since this code was written a while ago, it is not 2.0 friendly. 
2) Old pickles must be opened with the libraries at the same version when the pickle was made. 

Given that, I'm working on setting up a docker environment that will make it easier to use this code

**Comment by adelavega** [comment]
In the meantime I'm closing this issue in favor of #2

**Comment by adelavega** [comment]
Hey FY @AlexHatoum and @boredStats I added Docker support with #3.

Give it a whirl. I also updated to use the latest Neurosynth, and checked that all the libraries are pinned to the correct version.
